### PR TITLE
Integration testing

### PR DESCRIPTION
**Pull request by caolan**

### CODE REVIEW

**Comment by mandric** [comment]
Looks awesome!  Do you know offhand if there is any difference between selenium-webdriver and webdriverio?

**Comment by mandric** [comment]
Also will probably try to follow some patterns introduced here: https://github.com/mozilla/webextension-polyfill

**Comment by caolan** [comment]
> Looks awesome! Do you know offhand if there is any difference between selenium-webdriver and webdriverio?

WebdriverIO appears to be a test runner that wraps webdriver. There's a plugin for mocha which might be useful, but the tricky part is we need access to the driver object to configure the browser and include our temporary extension. I didn't see an obvious way to do that but that doesn't mean it's not possible.

**Comment by mandric** [comment]
Ok probably not much of a win there then.

**Pull request merged**
